apiVersion: v1
kind: Service
metadata:
  name: taskmanager-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.backend.port }}
