apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secrets.MONGO_URI | quote }}
  PORT: {{ .Values.secrets.PORT | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  CLIENT_URL: {{ .Values.secrets.CLIENT_URL | quote }}
  NEXT_PUBLIC_API_URL: {{ .Values.secrets.NEXT_PUBLIC_API_URL | quote }}
