apiVersion: v1
kind: Service
metadata:
  name: taskmanager-backend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.backend.port }}
{{- if and (eq .Values.service.type "NodePort") .Values.service.backendNodePort }}
      nodePort: {{ .Values.service.backendNodePort }}
{{- end }}
