apiVersion: v1
kind: Service
metadata:
  name: taskmanager-frontend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.port }}
{{- if and (eq .Values.service.type "NodePort") .Values.service.frontendNodePort }}
      nodePort: {{ .Values.service.frontendNodePort }}
{{- end }}
