apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskmanager-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/OletiSatishKumar/TaskManager_MERN_Infra_3.git'
    targetRevision: main                                      # Branch or tag
    path: infra/helm/taskmanager                              # Path to Helm chart
    helm:
      valueFiles:
        - values-dev.yaml                                     # Use dev values
  destination:
    server: 'https://kubernetes.default.svc'                 # Cluster API
    namespace: prod-namespace                                  # Target namespace for dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
