frontend:
  image: satishosk/taskmanager-frontend:master-20250603-0854
  replicas: 1
  port: 3000

backend:
  image: satishosk/taskmanager-backend:master-20250603-0854
  replicas: 1
  port: 5000

service:
  type: NodePort
