namespace: dev-namespace

frontend:
  image: :master-20250605-1522
  replicas: 1
  port: 3000  # container port frontend

backend:
  image: :master-20250605-1522
  replicas: 1
  port: 8000  # container port backend

service:
  type: NodePort
  backendNodePort: 31000
  frontendNodePort: 31100

secrets:
  MONGO_URI: "mongodb://localhost:27017/task_dev"
  PORT: "8000"            
  JWT_SECRET: "Satishkumar@@1234"
  CLIENT_URL: "http://localhost:3000"
  NEXT_PUBLIC_API_URL: "http://localhost:8000/api/v1"
